---
title: "q1_JD"
output: html_document
---
```{r setup}
library(readr)
library(forecast)
library(xts)
library(ggplot2)
library(reshape2)
library(dygraphs)
getwd()
library(dplyr)
library(fpp)
library(fpp3)
library(gridExtra)
library(tidyverse)
library(timetk)
# Setup for the plotly charts (# FALSE returns ggplots)
interactive <- TRUE
```

#Step 1 read the csv datasets files
```{r}
data = read.csv("Projectdata.csv")
data
```



```{r}
for (i in 2:7){
 pardata <- data[,c(1,i,i+6,i+12)]
 total_data <- melt(pardata, id="date")
 total_data$date <- as.Date(total_data$date) 
 allplot <- ggplot(data=total_data,
       aes(x=date, y=value,colour=variable,group = 1)) +
       geom_line() +
       scale_x_date(date_breaks = "years")
 print(allplot)
}
```

#transform to time series data
```{r}
data$date <- as.Date(data$date)  
tsdata <- ts(data[,2:19],start=c(2018,1),
         frequency=365.25)
tsdata
```


#Step 2 plot the data with acf and pacf
```{r}
for (i in 1:6){
 pardata <- tsdata[,c(i,i+6,i+12)]
 p <- dygraph(pardata)
 acf(pardata)
 pacf(pardata)
 print(p)
 }
```

#Step 3 check seasonality
```{r}
#function to plot hte decomposition
decomp.plot <- function(x, main = NULL, ...)
{
    if(is.null(main))
	main <- paste("Decomposition of", x$type, "time series")
    plot(cbind(observed = x$random + if (x$type == "additive")
        x$trend + x$seasonal
    else x$trend * x$seasonal, trend = x$trend, seasonal = x$seasonal,
        random = x$random), main = main, ...)
}

for (i in 1:18)
{
 monthdata <- ts(tsdata, frequency=12)
 seasondata<- decompose(monthdata[,i])
 decomp.plot(seasondata, main = colnames(monthdata)[i])
}

```

#Step 3 check seasonality: ADF test
```{r}
for (i in 2:18){
a <- adf.test(data[,i])
print(a)
}
```
